apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLables:
      batch: c42
  template:
    metadata:
      name: nginx
      lables:
        batch: c42
    spec:
      containers:
        - name: nginx
          image: nginx